stages:
    - test
    - deploy

job 0:
    stage: test
    tags:
        - test-runner
    script: 
        - python3 imperialcode/manage.py test

job 1:
    stage: deploy
    script: 
        - python3 imperialcode/manage.py runserver