stages:
    - test
    - deploy

job 0:
    stage: test
    tags:
        - test-runner
    script: 
        - pip3 install django
        - pip3 install psycopg2-binary
        - python3 imperialcode/manage.py test

job 1:
    stage: deploy
    script: 
        - python3 imperialcode/manage.py runserver
        - dpl --provider=heroku --app=hs5718-imperial-code --api-key= $HEROKU_API_KEY