stages:
    - test
    - deploy

test:
    stage: test
    tags:
        - test-runner
    script:
        - pip3 install django
        - pip3 install psycopg2-binary
        - pip3 install dj_database_url
        - python3 imperialcode/manage.py test


deploy:
  stage: deploy
  variables:
    HEROKU_APP: django
  only:
    - master
  image: ruby:2.5
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY
