stages:
    - test
    - deploy

test:
    stage: test
    tags:
        - test-runner
    script:
        - pip3 install django
        - pip3 install psycopg2-binary
        - pip3 install gunicorn
        - pip3 install dj_database_url
        - pip3 install django-heroku
        - pip3 install django_user_agents
        - python3 manage.py test


deploy:
  stage: deploy
  tags:
    - test-runner
  variables:
    HEROKU_APP: imperialcode
  only:
    - master
  image: ruby:2.5
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY
