stages:
    - test
    - deploy

job 0:
    stage: test
    script: 
        - apt-get install -y python3 python3-pip
        - pip install -r requirements.txt
        - python3 manage.py test

job 0:
    stage: deploy
    script: 
        - python imperialcode/manage.py runserver