stages:
    - test
    - deploy

test:
    stage: test
    tags:
        - test-runner
    script:
        - pip3 install django
        - pip3 install psycopg2-binary
        - pip3 install gunicorn
        - pip3 install dj_database_url
        - pip3 install django-heroku
        - python3 imperialcode/manage.py test


deploy:
  stage: deploy
  tags:
    - test-runner
  variables:
    HEROKU_APP: imperialcode
  only:
    - master
  image: ruby:2.5
  script:
    - kill $(lsof -t -i:8080) || true
    - export PORT=8080
    - python3 imperialcode/manage.py runserver 0.0.0.0:8080 &> /dev/null 2> /dev/null & disown
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY
